### PR TITLE
Binomial Functional Fast

### PR DESCRIPTION
**Pull request by jackmott**
Simple tweak to your functional implementation that is 3x faster and creates less GC pressure.

I could quite get my test program integrated nicely into your build system but you can grab it here:
 https://gist.github.com/jackmott/1fb6de0ea457b4ff3fc08ff0ac417926

Test Results -

```ini

Host Process Environment Information:
BenchmarkDotNet.Core=v0.9.9.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4712HQ CPU 2.30GHz, ProcessorCount=8
Frequency=2240907 ticks, Resolution=446.2479 ns, Timer=TSC
CLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
GC=Concurrent Workstation
JitModules=clrjit-v4.6.1590.0

Type=BinomialBenchmark  Mode=Throughput  Platform=X64  
Jit=RyuJit  

```
   Method | Steps |     Median |    StdDev | Scaled | Scaled-SD |    Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
--------- |------ |----------- |---------- |------- |---------- |--------- |------ |------ |------------------- |
     Func |  1000 | 45.0242 ms | 3.8548 ms |   3.14 |      0.26 | 2,305.00 |     - |     - |      14,153,009.97 |
 FuncFast |  1000 | 14.7078 ms | 0.3261 ms |   1.00 |      0.00 | 1,888.40 |     - |     - |      12,332,592.83 |

### CODE REVIEW

**Comment by hoonzis** [comment]
Hi Jack this looks good, by looking at the code it seems that you have replaced Lists, by Arrays and you were consistent unlike me before. For instance I was doing Seq.pairwise even when I knew the underlying collection was  a List.

So know this operates on Arrays and uses the Array function when possible. Is there something more in the commit that I have missed?

If not, maybe it could make sense to keep just your implementation and get rid of mine.

Regarding the benchmark, it should be quite easy to integrate, since this is using a fake so I will just add fake target for it - probably won't run it by appveyor, but at least one could run it locally anytime.

**Comment by jackmott** [comment]
Yes, just replacing list with arrays, because I  noticed you weren't doing anything with the collection that necessitated a list. Agree that you could just replace. I can do that in the PR and have a go at putting the test in again, or get it close and  you can tweak from there.

**Comment by hoonzis** [comment]
If you have the spare time just go ahead, otherwise I will try to get to it asap.

**Comment by hoonzis** [comment]
Hi,
I have merged the FuncFast and Func implementation into a single one. I also did a bit of cleanup and refactoring in the Binomial pricing part and added the Delta calculation to the Binomial pricing.
have a look if you are interested

**Pull request merged**
